// <auto-generated />
namespace diplom_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HomeWork12032018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HomeWork12032018));
        
        string IMigrationMetadata.Id
        {
            get { return "201803122140075_HomeWork12.03.2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
