// <auto-generated />
namespace diplom_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _13032018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13032018));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131528312_13032018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
