//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_revision_field_collection
    {
        public string entity_type { get; set; }
        public string bundle { get; set; }
        public sbyte deleted { get; set; }
        public long entity_id { get; set; }
        public long revision_id { get; set; }
        public string language { get; set; }
        public long delta { get; set; }
        public Nullable<long> field_collection_tid { get; set; }
    }
}
