//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class field_data_field_image
    {
        public string entity_type { get; set; }
        public string bundle { get; set; }
        public sbyte deleted { get; set; }
        public long entity_id { get; set; }
        public Nullable<long> revision_id { get; set; }
        public string language { get; set; }
        public long delta { get; set; }
        public Nullable<long> field_image_fid { get; set; }
        public string field_image_alt { get; set; }
        public string field_image_title { get; set; }
        public Nullable<long> field_image_width { get; set; }
        public Nullable<long> field_image_height { get; set; }
    }
}
