//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_managed
    {
        public long fid { get; set; }
        public long uid { get; set; }
        public string filename { get; set; }
        public string uri { get; set; }
        public string filemime { get; set; }
        public decimal filesize { get; set; }
        public sbyte status { get; set; }
        public long timestamp { get; set; }
        public string type { get; set; }
    }
}
