//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class node
    {
        public long nid { get; set; }
        public Nullable<long> vid { get; set; }
        public string type { get; set; }
        public string language { get; set; }
        public string title { get; set; }
        public int uid { get; set; }
        public int status { get; set; }
        public int created { get; set; }
        public int changed { get; set; }
        public int comment { get; set; }
        public int promote { get; set; }
        public int sticky { get; set; }
        public long tnid { get; set; }
        public int translate { get; set; }
    }
}
