//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxonomy_term_data
    {
        public long tid { get; set; }
        public long vid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string format { get; set; }
        public int weight { get; set; }
        public string language { get; set; }
        public long i18n_tsid { get; set; }
    }
}
